[package]
name = "montar"
version = "0.1.0"
authors = ["orasunis <orasunis@protonmail.com>"]

[dependencies]
tokio = "0.1"

serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

log = { version = "0.4", features = ["serde"] }
fern = "0.5"
chrono = { version = "0.4", features = ["serde"] }
